### ISSUE TITLE
code structure and linux support

### ISSUE THREAD

**Issue by kanakshilledar** [Aks132/Atomix-RISCV64#2]
Hi,
I am on linux and trying to build your project and getting stuck on build errors. I also found out some inconsistency in your code. Some of the includes start with `Include` where as some start with `include` any specific reason for them. Also can we rename the rootlevel `Include` directory to `include` to be consistent. Also your Makefile has `include` instead of `Include`.

I feel some of the imports are not optimized as well. Like in case of **Include/libc/Wprintf.h** the includes can be changed with
```c
#include "stdarg.h"
#include "../status.h"
#include "../uart/uart.h"
```
some more files need to follow this approach.
Also can we make the commits more explainable. I feel the current commits dont explain that well what is actually being changed. It will be better if we follow Linux kernel way of documenting the commits.

If you have any counter of why things are like that do let me know.

**Comment by deveshshevde** [comment]
@kanakshilledar hey kanak , Thanks for pointing out !
we will surely check builds on linux based distro & rectify our mistakes !!

**Comment by Aks132** [comment]
We have Addded Support for Linux.
